version: "3.7"

networks:
  my-network:

volumes:
  db:
  bundle:
  elasticsearch:
  redis:

services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    volumes:
      - redis:/data
    ports:
        - "6379:6379"
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 5s
      retries: 10
  db:
    image: mysql:latest
    container_name: mysql
    networks:
      - my-network
    volumes:
      - db:/var/run/mysqld
    restart: unless-stopped
    ports:
      - "33061:3306"
    expose:
    - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
      container_name: elasticsearch
      environment:
        - node.name=chat-system-node-1
        - cluster.name=es-docker-cluster
        - discovery.type=single-node
        - bootstrap.memory_lock=true
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - elasticsearch:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
      healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9200"]
          timeout: 5s
          retries: 10
  app:
    build: .
    container_name: chat-system-backend
    networks:
        - my-network
    volumes:
      - ./:/workspace
      - bundle:/bundle
    restart: always
    ports:
      - "3000:3000"
    environment:
      environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: chat_system_development
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    depends_on:
      - "db"
      - "elasticsearch"

  sidekiq:
    build: ./
    command: bundle exec sidekiq
    restart: always
    volumes:
      - ./:/workspace
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: chat_system_development
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    depends_on:
      - "db"
      - "app"
      - "redis"
      - "elasticsearch"